// Base
export const PURGE_DATABASE_ERROR = 'PURGE_DATABASE_ERROR';
export const PURGE_DATABASE_SUCCESS = 'PURGE_DATABASE_SUCCESS';
export const REQUEST_PURGE_DATABASE = 'REQUEST_PURGE_DATABASE';

// Cohort Analysis
export const FETCH_COHORT_ANALYSIS_ERROR = 'FETCH_COHORT_ANALYSIS_ERROR';
export const FETCH_COHORT_ANALYSIS_SUCCESS = 'FETCH_COHORT_ANALYSIS_SUCCESS';
export const REQUEST_FETCH_COHORT_ANALYSIS = 'REQUEST_FETCH_COHORT_ANALYSIS';

// Customers
export const FETCH_CUSTOMERS_ERROR = 'FETCH_CUSTOMERS_ERROR';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const REQUEST_FETCH_CUSTOMERS = 'REQUEST_FETCH_CUSTOMERS';
export const REQUEST_SEED_CUSTOMERS = 'REQUEST_SEED_CUSTOMERS';
export const SEED_CUSTOMERS_ERROR = 'SEED_CUSTOMERS_ERROR';
export const SEED_CUSTOMERS_SUCCESS = 'SEED_CUSTOMERS_SUCCESS';

// Orders
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const REQUEST_FETCH_ORDERS = 'REQUEST_FETCH_ORDERS';
export const REQUEST_SEED_ORDERS = 'REQUEST_SEED_ORDERS';
export const SEED_ORDERS_ERROR = 'SEED_ORDERS_ERROR';
export const SEED_ORDERS_SUCCESS = 'SEED_ORDERS_SUCCESS';