version: '2'
services:
  invitae_api:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://jason@db:5432/invitae_production
  db:
    image: postgres:9.6-alpine
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: jason
      POSTGRES_DB: invitae_production
